name: Hello Wolrd github-action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  hello-world:
    name: Un job para saludar
    runs-on: ubuntu-latest    
    steps:
      - name: 'Step Hola Mundo!'
        id: hello
        uses: alejandrofca/hello-world-docker-action@v2
        with:
          who-to-greet: "Alets"
      - name: Usar el output
        run: echo "La fecha fue ${{ steps.hello.outputs.time }}"
    